# version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-app
    ports:
      - "4000:4000"
    environment:
      - JWT_SECRET=723cb8399a2d3c36a0d4c0878069f8d1998fd5f1134b28626e332918c87b8fae
      - PORT=4000
    networks:
      - remote

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-app
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - remote

networks:
  remote:
    driver: bridge